# Generated by Django 4.2 on 2024-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
