# Generated by Django 4.2 on 2024-02-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
