# Generated by Django 4.2 on 2024-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_myuser_date_joined_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media/profile-pictures/default.jpg', null=True, upload_to='media/profile_pictures/', verbose_name='profile picture'),
        ),
    ]
