# Generated by Django 4.2 on 2024-03-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show_views',
        ),
    ]
