# Generated by Django 4.2 on 2024-03-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='view_count',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='views',
            new_name='view_count',
        ),
    ]
