# Generated by Django 4.2 on 2024-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media',
            field=models.FileField(upload_to='media/content/post/', verbose_name='post media file'),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='media',
            field=models.FileField(upload_to='media/content/story/', verbose_name='story media file'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
