# Generated by Django 4.2 on 2024-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_postmedia_media_alter_storymedia_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
    ]
